# -*- coding: utf-8 -*-
"""模拟电商/外卖业务数据。生产中这些数据应来自数据库,这里用内存字典模拟。"""

ORDERS = {
    "20260601001": {"order_id": "20260601001", "user": "u001",
                    "items": ["黄焖鸡米饭", "可乐"], "amount": 32.5,
                    "type": "外卖", "status": "配送中", "rider": "张师傅",
                    "eta": "12分钟", "address": "三号宿舍楼", "placed_min_ago": 38},
    "20260601002": {"order_id": "20260601002", "user": "u001",
                    "items": ["蓝牙耳机"], "amount": 199.0,
                    "type": "电商", "status": "已发货", "tracking": "SF1234567890",
                    "carrier": "顺丰", "eta": "次日达", "address": "三号宿舍楼",
                    "placed_min_ago": 600},
    "20260601003": {"order_id": "20260601003", "user": "u002",
                    "items": ["麻辣烫"], "amount": 26.0, "type": "外卖",
                    "status": "已送达", "rider": "李师傅", "eta": "已完成",
                    "address": "图书馆", "placed_min_ago": 120},
}

PRODUCTS = {
    "蓝牙耳机": {"name": "蓝牙耳机", "price": 199.0, "stock": 24, "rating": 4.6, "tag": "数码"},
    "黄焖鸡米饭": {"name": "黄焖鸡米饭", "price": 22.0, "stock": 999, "rating": 4.8, "tag": "外卖"},
    "麻辣烫": {"name": "麻辣烫", "price": 26.0, "stock": 500, "rating": 4.5, "tag": "外卖"},
    "机械键盘": {"name": "机械键盘", "price": 329.0, "stock": 8, "rating": 4.7, "tag": "数码"},
}

# 导购用扩展商品库。保留上面的 PRODUCTS 供原有简单商品查询使用;
# 个性化导购走这里,字段更接近真实电商推荐所需的决策信息。
PRODUCTS_EXT = [
    {
        "product_id": "p_ear_001",
        "name": "静听 Air 蓝牙耳机",
        "category": "蓝牙耳机",
        "brand": "SoundNest",
        "price": 269.0,
        "stock": 36,
        "rating": 4.7,
        "monthly_sales": 1280,
        "tags": ["主动降噪", "低漏音", "长续航", "通勤", "宿舍"],
        "scenarios": ["宿舍", "图书馆", "自习", "通勤"],
        "specs": {"battery_life": "单次7小时/总续航32小时", "noise_canceling": "ANC 38dB", "weight": "4.8g/单耳"},
        "review_summary": "降噪在人声和空调噪声场景表现稳定,漏音控制较好,佩戴轻便。",
        "risk_points": ["高频键盘声仍会听到一点", "耳帽尺寸需要试戴"],
        "store_name": "SoundNest校园数码店",
        "store_score": 4.8,
        "aftersale_score": 4.7,
    },
    {
        "product_id": "p_ear_002",
        "name": "漫声 Lite 降噪耳机",
        "category": "蓝牙耳机",
        "brand": "MeloBeat",
        "price": 199.0,
        "stock": 58,
        "rating": 4.5,
        "monthly_sales": 2360,
        "tags": ["性价比", "降噪", "低漏音", "轻便"],
        "scenarios": ["宿舍", "图书馆", "网课", "运动"],
        "specs": {"battery_life": "单次6小时/总续航28小时", "noise_canceling": "ANC 30dB", "weight": "4.5g/单耳"},
        "review_summary": "价格友好,图书馆小音量使用漏音少,续航够一天通勤和自习。",
        "risk_points": ["降噪深度不如高端款", "游戏低延迟模式一般"],
        "store_name": "漫声官方旗舰店",
        "store_score": 4.6,
        "aftersale_score": 4.6,
    },
    {
        "product_id": "p_ear_003",
        "name": "BassGo 青春版耳机",
        "category": "蓝牙耳机",
        "brand": "BassGo",
        "price": 129.0,
        "stock": 92,
        "rating": 4.2,
        "monthly_sales": 3100,
        "tags": ["低价", "重低音", "续航"],
        "scenarios": ["宿舍", "跑步", "短视频"],
        "specs": {"battery_life": "单次8小时/总续航30小时", "noise_canceling": "通话降噪", "weight": "5.2g/单耳"},
        "review_summary": "续航不错,低音量感强,适合日常娱乐。",
        "risk_points": ["无主动降噪", "安静环境大音量可能漏音"],
        "store_name": "BassGo数码专营店",
        "store_score": 4.3,
        "aftersale_score": 4.1,
    },
    {
        "product_id": "p_key_001",
        "name": "KeyPro 87 静音机械键盘",
        "category": "机械键盘",
        "brand": "KeyPro",
        "price": 459.0,
        "stock": 21,
        "rating": 4.8,
        "monthly_sales": 860,
        "tags": ["静音轴", "写代码", "游戏", "热插拔", "手感好"],
        "scenarios": ["宿舍", "办公室", "写代码", "游戏"],
        "specs": {"layout": "87键", "switch": "静音线性轴", "connection": "三模", "backlight": "白光"},
        "review_summary": "敲击声音克制,长时间写代码不累,游戏响应稳定。",
        "risk_points": ["没有数字小键盘", "白光不可调 RGB"],
        "store_name": "KeyPro外设旗舰店",
        "store_score": 4.8,
        "aftersale_score": 4.8,
    },
    {
        "product_id": "p_key_002",
        "name": "GameType K98 茶轴键盘",
        "category": "机械键盘",
        "brand": "GameType",
        "price": 399.0,
        "stock": 34,
        "rating": 4.6,
        "monthly_sales": 1420,
        "tags": ["性价比", "游戏", "手感好", "RGB"],
        "scenarios": ["游戏", "宿舍", "写代码"],
        "specs": {"layout": "98键", "switch": "茶轴", "connection": "有线/蓝牙", "backlight": "RGB"},
        "review_summary": "键位完整,段落感适中,适合游戏和日常输入。",
        "risk_points": ["夜间声音略明显", "键帽材质一般"],
        "store_name": "GameType外设店",
        "store_score": 4.5,
        "aftersale_score": 4.4,
    },
    {
        "product_id": "p_power_001",
        "name": "SafeCharge 10000mAh 充电宝",
        "category": "充电宝",
        "brand": "SafeCharge",
        "price": 119.0,
        "stock": 76,
        "rating": 4.7,
        "monthly_sales": 1980,
        "tags": ["轻便", "安全", "足容容量", "快充"],
        "scenarios": ["通勤", "图书馆", "短途旅行", "宿舍"],
        "specs": {"capacity": "10000mAh", "power": "22.5W", "weight": "185g", "certification": "CCC认证"},
        "review_summary": "容量标注可信,重量适合随身带,发热控制较好。",
        "risk_points": ["不能带动大功率笔记本", "只有一个 USB-C 口"],
        "store_name": "SafeCharge官方店",
        "store_score": 4.8,
        "aftersale_score": 4.7,
    },
    {
        "product_id": "p_mouse_001",
        "name": "SwiftClick 无线鼠标",
        "category": "鼠标",
        "brand": "SwiftClick",
        "price": 159.0,
        "stock": 43,
        "rating": 4.6,
        "monthly_sales": 1120,
        "tags": ["轻便", "静音", "无线", "办公", "游戏"],
        "scenarios": ["图书馆", "宿舍", "写代码", "轻度游戏"],
        "specs": {"dpi": "800-4000DPI", "weight": "78g", "connection": "2.4G/蓝牙"},
        "review_summary": "点击声小,手感轻,适合宿舍和图书馆使用。",
        "risk_points": ["大手用户可能觉得偏小", "不适合高强度 FPS"],
        "store_name": "SwiftClick外设店",
        "store_score": 4.6,
        "aftersale_score": 4.5,
    },
    {
        "product_id": "p_lamp_001",
        "name": "LumaCare 护眼台灯",
        "category": "台灯",
        "brand": "LumaCare",
        "price": 229.0,
        "stock": 65,
        "rating": 4.8,
        "monthly_sales": 1680,
        "tags": ["护眼", "宿舍", "阅读", "无频闪", "亮度可调"],
        "scenarios": ["宿舍", "图书馆", "阅读", "写作业"],
        "specs": {"brightness": "5档亮度", "color_temp": "三档色温", "certification": "国AA照度"},
        "review_summary": "照明均匀,低亮度夜间学习不刺眼,底座稳定。",
        "risk_points": ["需要插电使用", "灯臂不可完全折叠"],
        "store_name": "LumaCare校园生活馆",
        "store_score": 4.7,
        "aftersale_score": 4.6,
    },
]

# RAG 知识库原料:政策 / FAQ。每条是一段独立知识。
POLICIES = {
    "退货政策": "本平台支持7天无理由退货;生鲜及外卖食品因特殊性不支持无理由退货,但出现质量问题可申请赔付。",
    "配送时效": "外卖订单承诺30分钟内送达,若超过30分钟可在订单页申请超时红包补偿,补偿金额为订单金额的10%-30%。",
    "退款时效": "退款申请审核通过后,款项将在1-3个工作日内原路退回至支付账户。",
    "换货政策": "数码类商品支持15天内换货,需保持商品完好、配件齐全,运费由责任方承担。",
    "发票政策": "所有订单均可申请电子发票,在订单完成后30天内于订单详情页提交开票申请。",
}
