global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "guide-agent-app-compose"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

  - job_name: "guide-agent-app-k8s-port-forward"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "cadvisor"
    metrics_path: /metrics
    static_configs:
      - targets: ["cadvisor:8080"]

