apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: service-agent-lab

resources:
  - config.yaml
  - order-service.yaml
  - product-service.yaml
  - logistics-service.yaml
  - agent-app.yaml

images:
  - name: service-agent-lab
    newName: service-agent-lab
    newTag: latest
